In [1]:
import librosa

In [4]:
frequencies_hz = [0, 100, 500, 1000, 2000, 4000, 8000]

mel_values = librosa.hz_to_mel(frequencies_hz, htk = True)

print(mel_values)

[   0.          150.48910241  607.44591966  999.98553714 1521.35955416
 2146.06452751 2840.02304671]


In [ ]:
"""
In this context, htk=True means Librosa uses the HTK version of the Mel scale, which follows the classic formula:

m=2595log10(1 + f/700)
"""


In [6]:
hz_values = librosa.mel_to_hz(mel_values, htk= True)

print(hz_values)

[   0.  100.  500. 1000. 2000. 4000. 8000.]


In [7]:
#mel filter bank
import librosa

mel_filters = librosa.filters.mel(
    sr=16000,
    n_fft=2048,
    n_mels=80,
    fmin=0,
    fmax=8000
)

print(mel_filters.shape)

(80, 1025)


In [8]:
import numpy as np

# --------------------------------------------------
# Step 1: Power spectrum from 5 FFT bins
# --------------------------------------------------

power_spectrum = np.array([
    2.0,
    4.0,
    8.0,
    6.0,
    2.0
])

print("Power spectrum:")
print(power_spectrum)

# --------------------------------------------------
# Step 2: Manually define 2 Mel filters
# --------------------------------------------------

mel_filter_1 = np.array([
    0.0,
    0.5,
    1.0,
    0.5,
    0.0
])

mel_filter_2 = np.array([
    0.0,
    0.0,
    0.5,
    1.0,
    0.5
])

# Stack them into one filterbank matrix
mel_filterbank = np.array([
    mel_filter_1,
    mel_filter_2
])

print("\nMel filterbank shape:")
print(mel_filterbank.shape)

print("\nMel filterbank:")
print(mel_filterbank)

# --------------------------------------------------
# Step 3: Calculate each Mel-band energy manually
# --------------------------------------------------

mel_band_1 = np.sum(
    power_spectrum * mel_filter_1
)

mel_band_2 = np.sum(
    power_spectrum * mel_filter_2
)

print("\nMel band 1 energy:")
print(mel_band_1)

print("\nMel band 2 energy:")
print(mel_band_2)

# --------------------------------------------------
# Step 4: Store final Mel representation
# --------------------------------------------------

mel_energies_manual = np.array([
    mel_band_1,
    mel_band_2
])

print("\nManual Mel energies:")
print(mel_energies_manual)

# --------------------------------------------------
# Step 5: Same calculation using matrix multiplication
# --------------------------------------------------

mel_energies_matrix = (
    mel_filterbank @ power_spectrum
)

print("\nUsing matrix multiplication:")
print(mel_energies_matrix)

print(
    "\nSame result:",
    np.allclose(
        mel_energies_manual,
        mel_energies_matrix
    )
)

Power spectrum:
[2. 4. 8. 6. 2.]

Mel filterbank shape:
(2, 5)

Mel filterbank:
[[0.  0.5 1.  0.5 0. ]
 [0.  0.  0.5 1.  0.5]]

Mel band 1 energy:
13.0

Mel band 2 energy:
11.0

Manual Mel energies:
[13. 11.]

Using matrix multiplication:
[13. 11.]

Same result: True
